[package]
name = "sig"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
auth = { path = "../lib/auth" }
file-to-bytes = { path = "../lib/file-to-bytes" }
#load-private-key = { path = "../lib/load-private-key" }
byteorder = "1.3.1"
sha2 = "0.8.0"
#rsa = "0.1.3"
#rand = "0.6.5"
